### ISSUE TITLE
Wire cutting game impossible after installing Knowledge of Apollo

### ISSUE THREAD

**Issue by psznm** [bitburner-official/bitburner-src#698] opened 2023-08-01 23:32 UTC
On firstimage it is impossible to determine which wires should be cut to win the minigame. The only possible conclusion is that we should cut all the blue wires and keep the orange one. However after cutting wire number 2, the game was lost.

https://ibb.co/fk2d8G1

On second image different case of the bug is shown. What appears like should have won the minigame, has not won the minigame.

https://ibb.co/ws8hgjF

**Comment by d0sboots** [comment] 2023-08-02 00:39
Duplicate of #690

**Closed as completed by d0sboots** 2023-08-02 00:39 UTC
