### ISSUE TITLE
Bug: Scripts displayed offline gains miscalculation

### ISSUE THREAD

**Issue by Caldwell-74** [bitburner-official/bitburner-src#1006] opened 2024-01-01 04:35 UTC
Offline money gained from scripts and what the individual scripts show what they produced differ 
especially in situations where the runtime of a script is only a fraction of the time since last install
and when that script made the majority of the money gained from hacking

money gained from scripts while offline is here
https://github.com/bitburner-official/bitburner-src/blob/dev/src/engine.tsx#L266
based on total **money gained from scripts** and total **playtime since last aug**

scripts calculation is here
https://github.com/bitburner-official/bitburner-src/blob/dev/src/Script/ScriptHelpers.ts#L57-L60
based on the **individual scripts total money gained** and the **scripts online running time**

my understanding is that this massively inflates what the script shows it would have produced versus
what actually got produced

rosebuddy pointed towards that on discord here
https://discord.com/channels/415207508303544321/415207839246581781/1191135838118101143
one simplified  example 
10 hour install with only one hour of batching at the end that made 10t

script would show 10t / 1h 
game would actually give 10t / 10h

**Comment by HiEv** [comment] 2024-01-01 16:41
Possible duplicate of #1003.

**Comment by Caldwell-74** [comment] 2024-01-01 17:02
> Possible duplicate of #1003.

yeah that should be the same issue  but ill keep this open for anyone that to attempt to fix it

**Comment by Caldwell-74** [comment] 2024-01-01 17:03
dividing the individual scripts income by total time since install should fix it i think

**Closed as completed** 2024-02-10 12:24 UTC
