### ISSUE TITLE
macOS hot key Option+E  also types a special character after switching

### ISSUE THREAD

**Issue by BanovMiroslav** [bitburner-official/bitburner-src#823] opened 2023-09-22 14:37 UTC
On MacOS hot key Option+E to switch to Text Editor also types a special character after switching.

On macOS, using the option + E to switch to Editor also types a special character "´". Because option + key is used to type special characters on mac.
Version: steam current version as of 2023-09-22 changelog says v2.4.1 Update (8/26/23)

**Comment by myCatsName** [comment] 2023-09-22 15:59
It's a MacOS feature, like you said. I would guess it's not practical or appropriate for BB to override keyboard configs.

This looks like an easy fix to try individually - 

![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/0c65345e-039e-4d73-bc6a-d96a4fa00b3d)

**Comment by d0sboots** [comment] 2023-09-22 21:27
This is another manifestation of needing configurable keybinding. It's good to know that the current solution has issues with macs, since it was done the way it is now *because* of macs.

Duplicate of #420

**Closed as not planned by d0sboots** 2023-09-22 21:27 UTC
