### ISSUE TITLE
Typescript bug (probably something with imports and ts transpiling?)

### ISSUE THREAD

**Issue by Siri0n** [bitburner-official/bitburner-src#1851] opened 2024-12-15 04:14 UTC
[bitburnerSave_1734235243_BN1x1.json.gz](https://github.com/user-attachments/files/18138838/bitburnerSave_1734235243_BN1x1.json.gz)

My game version is v2.7.0 (Steam)

When I run 'run main.ts' in terminal, it works as intended (well, almost, I'm still working on my code),
But when I run 'run main.ts' in terminal again, script just fails silently after certain step.
After the first run, script editor pretends that my imports in main.ts are invalid. But if I change something unimportant in imported scripts and save them, script editor is satisfied.
If I edit and re-save all involved files, I could run main.ts as intended again.

Looks like there's some problem with ts transpiling or something like that.

**Comment by Siri0n** [comment] 2024-12-15 09:15
Oh. I think I understood. Script editor bug is independent of my module execution bug. Modules are persistent, and I save outdated ns object in jobRunner.ns.

Also, if modules are persistent, I don't need to communicate through ports, and my clever system is overengineered.

**Comment by catloversg** [comment] 2024-12-15 11:14
Duplicate of #1747.

**Closed as not planned** 2024-12-16 20:52 UTC
