### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by Sacha-Trct** [bitburner-official/bitburner-src#1108] opened 2024-02-18 20:02 UTC
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v2.3.2 (be426896)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
* Features: lang=fr-FR cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by LJNeon** [comment] 2024-02-18 21:19
This appears to be a duplicate of #527 and #358. More information would be useful.

**Comment by Snarling** [comment] 2024-03-04 15:03
Maybe there's at least a flag we can set to tell translation extensions not to try and translate the page, since this same issue keeps getting reported

@Sacha-Trct Can you confirm if you're using a translation extension (e.g. Google Translate)?

**Closed as completed** 2024-03-21 00:39 UTC
