### ISSUE TITLE
Hotkey "Zoom In" not working

### ISSUE THREAD

**Issue by ngschaider** [bitburner-official/bitburner-src#680] opened 2023-07-25 20:18 UTC
What is NOT working:
- Zooming in by pressing CTRL+PLUS to zoom in when using the plus near the letters.

What IS working:
- Zooming in by pressing CTRL+PLUS when using the plus on the numpad.
- Zooming in by pressing CTRL+SHIFT+PLUS when using the plus near the letters

- German QWERTZ keyboard layout
- OS: Linux (Kubuntu 23.04, Plasma 5.27.4)
- Version: Bitburner v2.3.1 (100030008) on Steam

**Comment by Hoekstraa** [comment] 2023-08-03 11:21
> German QWERTZ keyboard layout

Yeah, this seems to be a common thing.
This won't be an easy fix.
We've previously made changes to how keybindings are handled, due in part to how Macs pass them to the browser (see https://github.com/bitburner-official/bitburner-src/pull/242 and links within).

Best solution would be to implement custom keybindings so I'm closing this one as a duplicate of https://github.com/bitburner-official/bitburner-src/issues/420.

**Closed as not planned by Hoekstraa** 2023-08-03 11:21 UTC
