### ISSUE TITLE
Bladeburner success chance prediction fails at 0 population

### ISSUE THREAD

**Issue by Mavintyre** [bitburner-official/bitburner-src#1481] opened 2024-07-11 04:39 UTC
[bitburnerSave_1720672490_BN9x1.json.gz](https://github.com/user-attachments/files/16171512/bitburnerSave_1720672490_BN9x1.json.gz)

The title says it all, really. Attached is a save where Chonquing has 0 Synthoid population, and all my success chances are shown as 0~100%, although I think the actual success chance formula still works, since my actions were still succeeding.
Version is 2.6.2(633da3830)

**Comment by catloversg** [comment] 2024-07-11 10:16
Chonquing has 0 **estimated** Synthoid population, not 0 Synthoid population. If the Synthoid population drops to 0, the estimated success chance will be 0%. The success chance is usually a range (except some special cases), and the min value will be 0 if the **estimated** Synthoid population drops to 0.

**Comment by gmcew** [comment] 2024-07-27 17:47
Difference between actual and estimated populations may need clarification - closing this issue as it's working as intended

**Closed as not planned by gmcew** 2024-07-27 17:47 UTC
Labels: needs more info
