### ISSUE TITLE
Cannot load the game from NAS.

### ISSUE THREAD

**Issue by vb2007** [bitburner-official/bitburner-src#762] opened 2023-08-30 22:20 UTC
I've installed the game to the Y: disk (Y:\SteamLibrary\steamapps\common\Bitburner) directly from Steam, but couldn't manage to start it.
When I opened the game, it popped up the window with a white background, then instantly closed it.
I've tried installing the game to the C: drive, then it started and worked as expected.
The HDD is connected to a Raspberry Pi 4 device, and the device is sharing the drive's content (read & write) through a Samba server.
I had a save in the Steam cloud (I don't know if this info is relevant or not), but I couldn't manage to load any file, because as I've said the game crashed instantly.

Version: Bitburner v2.4.1

**Comment by d0sboots** [comment] 2023-08-30 22:39
The issue is very likely Samba. It doesn't implement the full file api that local filesystems do, especially in regard to locking. I've seen this issue with lots of other apps.

**Comment by vb2007** [comment] 2023-08-31 09:27
Thanks for the info. So far, every game worked for me from the network drive, that's why I flagged this as an issue (sure, the loading speed was slow, but they launched).
I'll keep it on my local drive then, it's not much data.

**Comment by Hoekstraa** [comment] 2023-10-24 08:32
I'm going to mark this with wontfix for now, as I'm not expecting this to be fixed. Let me know if you disagree!

**Closed as not planned** 2024-02-15 00:26 UTC
Labels: wontfix
