### ISSUE TITLE
InternalError: too much recursion (at "Active Scripts")

### ISSUE THREAD

**Issue by Caroline-Thies** [bitburner-official/bitburner-src#1187] opened 2024-03-22 20:48 UTC
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file - see below
- [x] Minimal scripts to reproduce the issue: I was running this script: [hack-manager.js.txt](https://github.com/bitburner-official/bitburner-src/files/14728248/hack-manager.js.txt)
- [x] Steps to reproduce - I left the script running for some time, when I came back it had crashed

### Environment

* Error: InternalError: too much recursion
* Page: Active Scripts
* Version: v2.6.0 (8154a4613)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: https://bitburner-official.github.io/dist/vendor.bundle.js

### Save
[RECOVERY_BITBURNER_1711139304(1).json](https://github.com/bitburner-official/bitburner-src/files/14728288/RECOVERY_BITBURNER_1711139304.1.json)

**Comment by gmcew** [comment] 2024-05-19 21:19
See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion) for more context on the error.
~~Reading through the attached script, I suspect the `distributeThreadsStaggered` function recurses forever if you fill the servers and `possibleThreads == 0`  while `toRun > 0`.~~ There's some infinite loops, but the example I referenced shouldn't trigger that error and I can't reproduce the error with your script or recovery file, unfortunately.
Closing the issue for now - I'll re-open if there's more information on game-based root cause. If any script troubleshooting is needed, swing by the discord!

**Closed as completed by gmcew** 2024-05-19 21:19 UTC
Labels: needs more info
