### ISSUE TITLE
TypeError: Cannot add property return, object is not extensible (at "Work")

### ISSUE THREAD

**Issue by doomja** [bitburner-official/bitburner-src#407] opened 2023-03-05 00:57 UTC
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
   - provided
- [x] Minimal scripts to reproduce the issue
   - don't believe I had any scripts running at the time of issue
- [x] Steps to reproduce
   - open game on existing save > allow game to run job position and continue farming > add a hacknet node > max node > continue to be inactive and allow game to farm

### Environment

* Error: TypeError: Cannot add property return, object is not extensible
* Page: Work
* Version: v2.2.2 (6eb5b5ab)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
[bitburnerSave_1677977470_BN1x1.zip](https://github.com/bitburner-official/bitburner-src/files/10890501/bitburnerSave_1677977470_BN1x1.zip)
```

Thank you for your time!

**Comment by Snarling** [comment] 2023-03-07 10:48
I have not been able to reproduce this so far, and looking through the internal code I'm not sure where this would be occurring. Further troubleshooting will probably need to wait until we get either more reports or a more reliable repro method

**Comment by gmcew** [comment] 2024-05-21 20:23
I also cannot reproduce with the save and info provided, so will close this until something new comes to light

**Closed as completed by gmcew** 2024-05-21 20:23 UTC
Labels: needs more info
