### ISSUE TITLE
External IDE file syncing broken with v2.2.2 (d3f9554a)

### ISSUE THREAD

**Issue by robinedmunds** [bitburner-official/bitburner-src#381] opened 2023-02-22 17:34 UTC
v2.2.2 (d3f9554a)

My client updated to the above version today via Steam, and now external IDE file syncing has stopped working.

I tried stopping and starting the API Server, re-generating the API key. No error shows anywhere.

Using VS Code with the **Bitburner VSCode Integration v1.3.3** extension.

**Comment by Snarling** [comment] 2023-02-23 02:29
Duplicate of #383, closing this one because the other has more info.

**Closed as completed by Snarling** 2023-02-23 02:29 UTC
