### ISSUE TITLE
on file load normalise all file names

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#11] opened 2022-10-19 17:55 UTC
[hydroflame]
null

**Comments From Original Issue**

[phyzical]
> this one im not sure about.
>  is it just a matter of making this exportable  https://github.com/danielyxie/bitburner/blob/dev/src/Electron.tsx#L35 exportable
> 
> and calling it here? https://github.com/danielyxie/bitburner/blob/dev/src/db.tsx#L44

**Comment by Snarling** [comment] 2022-10-25 14:53
Closing as duplicate of / part of #10

**Closed as completed by Snarling** 2022-10-25 14:53 UTC
