### ISSUE TITLE
When switching bitnodes if the auto save has not occurred and you close the game it could leave you in a bad state.

### ISSUE THREAD

**Issue by soshimozi** [bitburner-official/bitburner-src#1325] opened 2024-05-29 17:09 UTC
Bitburner v.2.6.1 (d2c7b2504)

Steps to reproduce:
Destroy bitnode and choose a different bit node, e.g. 1.3 to 2.1.  Quit game before auto save occurs.

Observation:
When starting Bitburner it loads the last save file which occurred before you destroyed the bitnode.  If you have already backdoored world demon you wind up in a stuck state.  No b1tflume.exe either to exit.  You are essentially in a broken state and will need to reload from last save.

Expected:
Game loads fine and maintains previous state. 

Suggestion:
A quick fix for this could be to just autosave when switching bitnodes.  That will ensure the local save file matches and won't leave you in a broken state.

**Comment by d0sboots** [comment] 2024-05-29 18:37
There is an achievement for sitting in the BN selection screen for an hour, so if the game is broken by saving in that state, then autosaving after won't cut it as a fix.

**Comment by Caldwell-74** [comment] 2024-05-29 19:13
the bitnode selection is sadly not its own "area"
its just a curtain thats pulled up while in the background you are still inside the bn
the real transition happens when you enter

maybe backdoor needs a special check to trigger the "curtain" even when world daemon is already backdoored?

**Comment by soshimozi** [comment] 2024-05-29 22:16
> the bitnode selection is sadly not its own "area" its just a curtain thats pulled up while in the background you are still inside the bn the real transition happens when you enter
> 
> maybe backdoor needs a special check to trigger the "curtain" even when world daemon is already backdoored?

I think that's the real fix honestly.  I didn't have the choice to backdoor world daemon, since it was already backdoored, and I sat there for probably an hour with nothing happening.  I was still making money, since I was in 8.2 and had my scripts running, but it never triggered the bitnode selection.  I always backup when adding augs (you get +1 favor sometimes ;) ), so I recovered from there.  Interestingly though, it kind of ignored it and resorted my save even I told it not to.  I ended up just resetting and then loading from that previous backup which put me back in the state with the red pill.  By that time my hacking was high enough that it only took me about 10 minutes to hit 3k and I was on my way.

**Comment by Kelenius** [comment] 2024-05-30 12:02
If the WD is backdoored and you're still in the bitnode, you can still manually hack it to finish.

**Comment by soshimozi** [comment] 2024-05-30 15:59
Okay, so I just hack() the server and that will open the bitnode?  I wasn't
aware of that and it's not really obvious, but good to know.  It sounds
like there is a work around, so I'll close this now.

**Comment by Kelenius** [comment] 2024-05-30 17:26
I think it's still an issue because this is not mentioned anywhere in the game that you can do that. It can create a confusing situation. It's just not a softlock.

**Comment by catloversg** [comment] 2024-05-31 14:00
@soshimozi Can you clarify the "broken state"? If you install a backdoor on WD and reload the game before entering a new BN (no matter if autosave occurs or not), you can just install a backdoor again and enter the BitVerse UI.

**Comment by TheAimMan** [comment] 2024-05-31 14:02
> @soshimozi Can you clarify the "broken state"? If you install a backdoor on WD and reload the game before entering a new BN (no matter if autosave occurs or not), you can just install a backdoor again and enter the BitVerse UI.

I was about to comment on this :)
I attempted to reproduce in Dev by using Dev Tools to backdoor the WD before I called any of the commands.
Both singularity and the terminal command successfully brought me to the BN selection page.
Looking at the code neither one checks to see if it's already been backdoored to stop you from doing it again.

**Comment by Kelenius** [comment] 2024-05-31 14:26
> you can just install a backdoor again

I actually didn't know that, but I think it's still a problem - having the WD be backdoored is misleading and makes it seem like you got stuck, even if you actually aren't.

You know, I think there's actually a very easy way to fix this: when WD is backdoored, don't actually set it to be backdoored, just kick the player into the BN selection screen. That way if someone triggers this (backdoors the WD, then refreshes), they won't be confused by the WD having a backdoor installed. It'll just look like they never backdoored it in the first place.

**Comment by TheAimMan** [comment] 2024-05-31 14:32
I think you'd just need to move line 303 to line 311, so WD never actually backdoors the server when called from the terminal.

https://github.com/bitburner-official/bitburner-src/blob/54d099e552102d51d0b90baf0ed164a8b8e06a0e/src/Terminal/Terminal.ts#L303

**Comment by catloversg** [comment] 2024-05-31 16:04
Faking the backdoored status by not setting `backdoorInstalled` while showing the BitVerse UI is a dangerous band-aid fix for this issue. There are other logic code that depend on `backdoorInstalled` of WD. For example, `bitNodeFinishedState` in `src\Achievements\Achievements.ts` checks that property. Doing that will create more bugs.

Reproducible test case:
- Use a clean save file.
- Use Dev menu to add any SF (`knowsAboutBitverse`).
- Use Dev menu to get enough Hacking skill, augmentations, etc.
- Install a backdoor on WD.

Result: get `FAST_BN` achievement.
If we "fake" the backdoored status, we won't get that achievement.

**Comment by Caldwell-74** [comment] 2024-05-31 16:14
the load of a savegame could check for wd beeing backdoored and then route to the bitverse

**Comment by Kelenius** [comment] 2024-05-31 16:57
> There are other logic code that depend on `backdoorInstalled` of WD.

Then that's also a problem because you can also destroy WD by hacking it, so all of those things wouldn't trigger.

**Comment by d0sboots** [comment] 2024-05-31 22:09
Manually hacking installs a backdoor.

**Comment by catloversg** [comment] 2024-06-01 04:31
> Then that's also a problem because you can also destroy WD by hacking it, so all of those things wouldn't trigger.

Just as d0sboots said, manually hacking installs a backdoor. `bitNodeFinishedState` also checks `numBlackOpsComplete` for Bladeburner route.

**Comment by soshimozi** [comment] 2024-06-01 14:31
> > Then that's also a problem because you can also destroy WD by hacking it, so all of those things wouldn't trigger.
> 
> Just as d0sboots said, manually hacking installs a backdoor. `bitNodeFinishedState` also checks `numBlackOpsComplete` for Bladeburner route.

You are assuming all players will be looking at source code.  It's a casual game and I know a lot of non-programmers who play this game.  They have become programmers ;) playing this game, but it's not their focus.  Some of us live by the code and die by the code, but not so much for others.  Just saying it could be a better user experience if it was more obvious.  Your choice, but I can close this since it works as expected, but with a suggestion for documentation or some other method of communication to the end user.  Just because it works as expected doesn't mean the way it works is good :D

** Edit - also scripting returns true for backdoorInstalled.  I use scripts to help me manage my hacking/backdooring.  When the API tells me it's already been backdoored, it's not so obvious what I need to do.

**Comment by catloversg** [comment] 2024-06-01 15:54
I do not assume that all players will be looking at source code. I don't know why you get that idea. The comment that you quoted (and the previous ones in the chain) shows that faking the backdoored status is problematic, and we need a better way to deal with this issue. Cald's suggestion is a better solution for UI.

**Closed as completed** 2024-06-08 20:54 UTC
Labels: bug
