### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by tjwlstj** [bitburner-official/bitburner-src#1682] opened 2024-10-06 14:54 UTC
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v2.3.2 (be426896)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Whale/3.28.266.11 Safari/537.36
* Features: lang=ko cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by catloversg** [comment] 2024-10-06 15:50
This is very likely the duplicate of #527.

@tjwlstj If you are using a translation service/extension or anything that can alter the web page, you have to disable it.

**Comment by catloversg** [comment] 2024-10-06 15:51
This is very likely a duplicate of #527.

@tjwlstj If you are using a translation service/extension or anything that can alter the web page, you have to disable it.

**Comment by gmcew** [comment] 2024-10-13 18:45
There's a bit more detail in #527 and the other related occurences; closing this as a duplicate

**Closed as not planned by gmcew** 2024-10-13 18:45 UTC
