### ISSUE TITLE
Hamming code leading zeroes are confusing

### ISSUE THREAD

**Issue by BanovMiroslav** [bitburner-official/bitburner-src#826] opened 2023-09-23 18:25 UTC
There are two coding contracts relating to Hamming codes. One of them gives example of how integers are encoded to hamming codes and asks you to encode one, and the other one gives a hamming code with possible flipped bit and asks for the integer.

The issue is that the first one does not expect leading zeroes, and the second one does contain leading zeroes in the hamming code. This is confusing and actually caused me to wonder if the problem was with the endianness instead, which is also mentioned in both of the coding contracts. This was provided for the contract "HammingCodes: Encoded Binary to Integer" - 0100100010111000010001101000001111101011001001111010110100000001

Here is how decoding it and re-encoding without leading zeroes gives different results:

```
{
  hammingInput: '0100100010111000010001101000001111101011001001111010110100000001',
  binaryFromHamming: '000001110001000110100000111101011001001111010110100000001',
  integerFromBinary: 3979415699041537,
  binaryFromInteger: '1110001000110100000111101011001001111010110100000001',
  hammingFromBinary: '00010110000100010101000001111010011001001111010110100000001'
}
```

So I am not sure, maybe zero padding is correct. But I think there shouldn't be two implementations, and only one should be used. Or maybe make a mention in the contract that the value may have zero padding to make it a square matrix or something like that.

Version of game: v2.4.1 (8/26/23)

**Comment by d0sboots** [comment] 2024-02-29 04:18
*Technically*, the 2nd form (the one asked for in Integer to Encoded Binary) isn't a true Hamming Code, because they operate with a block size of 2^n - 1. (2^n for extended Hamming Codes, which is what the problem is dealing with.) Rather, it's a truncated Hamming Code.

Probably it would make more sense to round up the block size to a power of two, and then the two would match up. However, this would break all the existing contract solvers out there...

**Comment by gmcew** [comment] 2024-05-19 11:39
Enhancement label for script-breaking consistency change - terminology in UI should be fixed by above PRs

**Closed as completed** 2024-05-23 07:45 UTC
Labels: enhancement
