### ISSUE TITLE
BUG: Faction favor preview can overestimate by 1

### ISSUE THREAD

**Issue by SansForSSBU** [bitburner-official/bitburner-src#1714] opened 2024-10-22 00:53 UTC
Steps to reproduce:
Look at faction favor preview
Wait until it increases by 1, then install augments relatively quickly after that happens.
After installing augments, re-join the faction. You will likely have 1 less favor with that faction than the preview said you would have.

I recorded a video, if it's any help: 
Key timestamps: 
0:03: Favor ticks over
1:00: I show the favor preview, then install augments.
4:20: I re-join the faction and show that the favor is 1 less than the preview said it would be.

https://www.youtube.com/watch?v=Af0fMQFZuvE

Version: Bitburner 2.6.2 (633da3830)

**Comment by d0sboots** [comment] 2024-10-22 04:07
Hmm. This is a real mystery, because the way they are calculated in the source is exactly the same.

**Comment by d0sboots** [comment] 2024-10-22 04:15
Moreover, I can't reproduce this. When I installed augments, it predicted I would have 467.303 favor with the black hand, and that is precisely what I had down to the 3rd decimal. So something specific is happening with your game in particular.

**Comment by d0sboots** [comment] 2024-10-22 04:20
Aha, you are still playing on 2.6.2. I think this is already fixed by #1530.

**Closed as completed by d0sboots** 2024-10-22 04:20 UTC
