### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length') (at "Terminal")

### ISSUE THREAD

**Issue by GoulartNogueira** [bitburner-official/bitburner-src#1478] opened 2024-07-09 19:42 UTC
### How did this happen?

I had an error and now I cannot open the game.
Honestly, I have no idea on what caused this error.
I'm just submitting it in case anyone may have a similar issue, so we can prioritize bug fix, or to help identifying the bug, by common patterns.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'length')
* Page: Terminal
* Version: v2.6.2 (633da3830)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/2.6.2 Chrome/116.0.5845.228 Electron/26.3.0 Safari/537.36
* Features: lang=en-GB cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save

[RECOVERY_BITBURNER_1720553493.json.gz](https://github.com/user-attachments/files/16149493/RECOVERY_BITBURNER_1720553493.json.gz)

**Comment by GoulartNogueira** [comment] 2024-07-09 19:49
Update:
I restarted the game. Somehow, now it works.
Bug is gone. I still have no clue what just happened.

**Comment by d0sboots** [comment] 2024-07-09 20:00
I can think of some ways this can happen. If you have a bug in one of your scripts such that you end up redefining one of the fundamental js objects like "String" for instance. We put in protections for String and Object, but there are surely others that are still capable of crashing the game if you set them to undefined. Ah, JavaScript...

**Comment by d0sboots** [comment] 2024-07-09 20:02
If it happens again and you can narrow it down to running one of your scripts, please post the script.

**Comment by HiEv** [comment] 2024-08-04 00:24
This is now a (less detailed) duplicate of bug #1482 "[BUG] Game broke on terminal history search - TypeError: Cannot read properties of undefined (reading 'length') (at "Terminal")".

As such, this issue should probably be closed.

**Comment by d0sboots** [comment] 2024-08-04 06:20
Good catch. I will close as dupe for now, but it's good to recognize that this has been reported twice (and this probably happened more than twice)

**Closed as not planned by d0sboots** 2024-08-04 06:20 UTC
Labels: needs more info
