### ISSUE TITLE
File drag and drop in ScriptEditor doesn't update UI correctly + Cursor location is partially lost when switching between files.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#326] opened 2023-01-16 08:36 UTC
I'm viewing a large script.  I scrolled down to line 898 (mentioned in an error message) then switched to another file.  Returning to the first file starts again at line 1.

Tried it again and it happens again.  Even tried clicking on the line I care about to stay there...still returned to line 1.

I can't say when this happens or not, but it's really annoying.  This isn't the first time I've been annoyed by this.  File I used was by Troff for BladeBurner automation https://steamcommunity.com/sharedfiles/filedetails/?id=2837856721

**Comment by OneOfMany07** [comment] 2023-01-18 11:12
Also dragging and dropping the files to change order doesn't update the UI.  I have to click on the old title to get it to change.  Makes it look like the swap didn't happen.  And if you try it again they swap back to the way you started at.

1. Open 2+ files in script editor.
2. Drag and drop the title of some file to another location (left or right), dropping it where you wish it to appear.  I often hold the title for a moment to make sure the UI recognizes something should change.
When you let go the titles will flash to what it should be, but then revert to the wrong names again.

I hesitate to file a whole new bug for this problem.  I have no idea if you're using some other package that could be updated or have a bug filed against it for stuff like this.

**Comment by Draco18s** [comment] 2023-01-19 05:29
The cursor position that is saved is the *last edited* location. But yes, it is annoying.

**Comment by Snarling** [comment] 2023-02-21 11:36
> Also dragging and dropping the files to change order doesn't update the UI

This is a bitburner bug.

I'm not sure if the cursor memory stuff is a limitation of Monaco or if it's something we can fix, will need to be looked into.

**Comment by gmcew** [comment] 2024-05-19 07:38
The first issue of cursor location memory is repeated #682
The second issue for editor UI failing to re-render correctly on moving tabs around I suspect was closed during PR #886 , as I cant reproduce it on steam or firefox currently.

I'm closing this one for the UI bug specifically, the cursor location issue will be kept through issue mentioned above.

**Closed as completed by gmcew** 2024-05-19 07:38 UTC
Labels: UI bug
