### ISSUE TITLE
Shortest Path on a Grid contract via API does not accept an empty string as a solution

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#119] opened 2022-10-19 18:10 UTC
[Draco18s]
Open attached save and connect to Syscore if the save doesn't take you there (`home; connect harakiri-sushi; connect CSEC; connect omega-net; connect avmnite-02h; connect syscore`). Run the contract and confirm visually that no path exists. Return home and `run findcontracts.js --submit --oftype "Shortest Path in a Grid"`

Expected output:
 - `findcontracts.js: Result: Gained 17500 faction reputation for Sector-12`

Actual output:
 - `findcontracts.js: Reward blank! syscore contract-384448-Sector-12.cct answer: `

Return to Syscore, run the contract, and click submit, leaving the answer field blank. Note that this was the correct answer.

So not only does `codingcontract.attempt` not return a *success* value for a correct answer, but it doesn't even return a *failed attempt.*

- [x] Save file [bitburnerSave_1665085206_BN3x1.zip](https://github.com/danielyxie/bitburner/files/9728135/bitburnerSave_1665085206_BN3x1.zip)
- [x] Minimal scripts to reproduce the issue [paths2.zip](https://github.com/danielyxie/bitburner/files/9728144/paths2.zip) (`paths2` can be run directly, the same method is imported into the autosolver `findcontracts`).
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0

**Comments From Original Issue**

[Snarling]
> It does accept an empty string.  Your error must be in your script because directly submitting an empty string leads to a success.
> 
> ![image](https://user-images.githubusercontent.com/84951833/194814011-83ea922d-bb1e-4484-8bb3-05e0957811df.png)
>

**Comment by Snarling** [comment] 2022-10-19 20:45
@Draco18s See attached image, I was able to load your save and directly submit empty string via a script and it was accepted and provided the correct reward text. I'm closing this issue but if you can demonstrate that this happens as a game bug and not a bug in your script, we can reopen this.

**Closed as completed by Snarling** 2022-10-19 20:45 UTC
