### ISSUE TITLE
Enums do not compile correctly to javascript.

### ISSUE THREAD

**Issue by Nepomuceno** [bitburner-official/bitburner-src#1198] opened 2024-03-28 19:57 UTC
The current way that enums are created they do fail when conpiling typescript to javascript giving no reference to @ns.js 

```ts
import { NS, CityName, GymType, LocationName } from "@ns";

export async function main(ns: NS): Promise<void> {
  ns.tprint(CityName.Sector12);
  ns.tprint(LocationName.Sector12PowerhouseGym);
  ns.tprint(GymType.agility);
}
```

this would fail with 

`Error while calculating ram usage for this script. No such file on server: "@ns.js"`

changing the enums to const enum does fix that.

**Comment by d0sboots** [comment] 2024-03-28 21:33
As the error message states, the issue here is that there is no @ns to import from. In the game, everything in NetscriptDefinitions.d.ts is included by default, with no need to import. You appear to be using typescript externally, so the issue here is your configuration.

**Comment by Nepomuceno** [comment] 2024-03-28 21:54
I am just following the default template in the docs to code from vscode.

**Comment by Snarling** [comment] 2024-04-08 10:31
The problem is that the enums are actually runtime objects, and the type in NetscriptDefinition.d.ts does not export a runtime object because it is a .d.ts file, and has to use `declare enum` for the runtime enum.

Using the ingame IDE and regular js, which is the normal method for authoring scripts, player access to enums is through ns.enums, which provides runtime objects for some of the game's enums. In order to properly describe the shape of that runtime object, we have to declare an enum vs using a const enum in the API definition file.

I'm open to a solution that makes it work for both use cases, but I'm not sure there is one that can be implemented on the game's end. It might be fixable on the external editor side by having some processing that substitutes enum member references in your code with the string literals (as if the enums were const enums).

**Comment by gmcew** [comment] 2024-05-21 17:48
From the above: this appears to be a fundamental limitation of how the game interacts with external editors. If a solution works that covers both grounds - that PR can link back to this, but for now I'm closing it.

**Closed as completed by gmcew** 2024-05-21 17:48 UTC
Labels: wontfix
