### ISSUE TITLE
Error calculating export in corpo with formulas: SyntaxError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by mathaefele** [bitburner-official/bitburner-src#603] opened 2023-06-12 13:05 UTC
Hi, 

I'm putting the formula `(-10*IPROD-IINV)/10` in my plant exports of agriculture division (whose name is ZolAgro). Namely two export: one towards the tobacco division and one towards the real estate division. By setting the smart supply option of the receiving divisions to 'use leftovers', this formula exports the full production as long as the current stock is zero. (At least that's the plan)

It works pretty nicely until the real estate division production saturates due to a lack of storage. Then, looking at figures of the plants stock of the real estate division, I can see a '-0.00' plants appearing sometime and that's when I see a error window popping up with:
```
Calculating export for Plants in ZolAgro's Sector-12 division failed with error: SyntaxError: Invalid left-hand side expression in postfix operation
```
Maybe I am doing something wrong or something needs to be fixed.

- running v2.3.1 (Steam version as of 12/06/23)

Thanks
Cheers
Mat

**Comment by mathaefele** [comment] 2023-06-12 15:06
Well, looking at other divisions, I can also see -0.00 for stock values, so this does not look like a relevant hint...

**Comment by ABruel** [comment] 2023-06-12 16:57
From testing, this happens if IINV ever goes negative. Don't know why it would go negative (maybe that's because I haven't gotten to this part of the game yet), but IPROD doesn't seem to have this problem so it's probably IINV. 

![image](https://github.com/bitburner-official/bitburner-src/assets/30672118/572330e7-9718-46cc-8772-553ffa3ed46f)

Maybe try changing your formula to `(-10*IPROD-(IINV))/10` until this gets corrected.

**Comment by d0sboots** [comment] 2023-06-12 19:24
I know what the issue is, I thought Snarling fixed it in a certain PR but didn't actually check, so that's on me :P

**Comment by mathaefele** [comment] 2023-06-13 15:09
> From testing, this happens if IINV ever goes negative. Don't know why it would go negative (maybe that's because I haven't gotten to this part of the game yet), but IPROD doesn't seem to have this problem so it's probably IINV.
> 
> ![image](https://user-images.githubusercontent.com/30672118/245213196-572330e7-9718-46cc-8772-553ffa3ed46f.png)
> 
> Maybe try changing your formula to `(-10*IPROD-(IINV))/10` until this gets corrected.

This works, at least I do not get the popping error message anymore, thanks

**Comment by d0sboots** [comment] 2023-06-19 00:27
Fixed by <https://github.com/bitburner-official/bitburner-src/commit/c7d05cae5888335fc58b5f023665668def57b54a> (no PR)

**Closed as completed by d0sboots** 2023-06-19 00:27 UTC
Labels: bug
