### ISSUE TITLE
Gang: Wanted level evolution value off by ca. 0.005/sec

### ISSUE THREAD

**Issue by arnauddub** [bitburner-official/bitburner-src#1015] opened 2024-01-02 21:50 UTC
I observed in the gang Management tab that the true wanted level increase is about 0.005/sec less then the displayed evolution

This is mostly noticeable for growth values very close to zero (0.00xxx / sec with xxx < 500), where the evolution of the "Wanted level" displays a positive value (increase) while the wanted level is in fact decreasing. 

Corresponding save (although probably easily reproducible by reaching lower wanted growth values on any save)
[bitburnerSave_1704228885_BN4x1.json](https://github.com/bitburner-official/bitburner-src/files/13814126/bitburnerSave_1704228885_BN4x1.json)

**Comment by arnauddub** [comment] 2024-01-02 22:05
After further testing, the offset doesn't seem constant but always in the direction of a lower increase (or a higher decrease) of wanted level.

**Comment by cigarmemr** [comment] 2024-01-03 01:03
Checked the save and confirmed. Looks like it is caused by the task "Ethical Hacking" but no exact clue is found.

**Comment by cigarmemr** [comment] 2024-01-03 16:28
Finally I've found it. The code inside [Gang.ts#L152](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Gang/Gang.ts#L152) contains a "safeguard" for unknown reason:
```javascript
    if (!(this.wanted === 1 && wantedLevelGainPerCycle < 0)) {
      const oldWanted = this.wanted;
      let newWanted = oldWanted + wantedLevelGainPerCycle * numCycles;
      newWanted = newWanted * (1 - justice * 0.001); // safeguard
      // Prevent overflow
      if (wantedLevelGainPerCycle <= 0 && newWanted > oldWanted) newWanted = 1;
```
Note that `justice` is the number of gang members that are performing tasks which has a negative `baseWanted` (namely "Ethical Hacking" and "Vigilante Justice"). This makes the new wanted level calculated taking a roughly 0.1% decrement per cycle per member.
However, the number displayed in the Management page is obtained directly from 'calculateWantedLevelGain()' without affected by the "safeguard".

So this is confirmed: Every member assigned to the "wanted level suppressing" tasks will lower wanted level a bit more than expected.
From the comment "safeguard" I guess it is to ensure "justice" members are always capable to lower wanted level efficiently, even if they are newly recruited and have poor stats.

**Comment by LJNeon** [comment] 2024-03-06 22:16
It looks like the safeguard is applied to the total wanted level, not to the gains, and it's only applied when wanted level is >1 or gains aren't negative.

The obvious fix here seems to be including the effects of the safeguard in `this.wantedGainRate`. If I'm not missing anything and no one else opens a PR in the next day or so I'll open a PR to fix this.

**Comment by Snarling** [comment] 2024-03-08 01:19
The safeguard is basically to allow recovering the gang if the wanted / respect ratio gets too high (e.g. a member who had most of the gang's respect dies or gets ascended while the wanted level was high). That can result in a very steep wanted penalty, and without this rescue mechanic in place, it can take an insane amount of time to get the wanted penalty back down to something manageable.

In the past we've talked about the fact that it creates an inaccuracy in the displayed wanted rate, but it's not really a big deal because it's only ever inaccurate in the player's favor.

**Closed as completed** 2024-03-08 04:46 UTC
