### ISSUE TITLE
Wilson Analytics stops working after reaching max Awareness and Popularity

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#622] opened 2023-06-17 07:16 UTC
Wilson Analytics stops working after reaching max Awareness and Popularity (1), 
despite that "Advertising Multiplier" (2) is far from max:

Advertising Multiplier is frozen and not affected by buying Wilson Analytics.

![2023-06-17 10_07_29-Bitburner v2 3 1 (100030008)_Advert](https://github.com/bitburner-official/bitburner-src/assets/20597249/2857b38c-1fcc-4a28-9126-661af0777122)

**Comment by d0sboots** [comment] 2023-06-17 07:20
But advertising multiplier only affects awareness and popularity... You're just throwing your money away at this point.

**Comment by AssenD** [comment] 2023-06-17 07:47
Are you certain?

I thought it affects also the price of products, so I expected it to work as said here:

![2023-06-17 10_42_09-Bitburner v2 3 1 (100030008)_3](https://github.com/bitburner-official/bitburner-src/assets/20597249/ff60e6b3-fe45-466e-bef7-cabb25ef761e)

**Comment by d0sboots** [comment] 2023-06-17 08:46
> due to its awareness and popularity

It affects sales by boosting awareness and popularity. If those are capped, Wilson (and advert) don't do anything further.

Incidentally, once one of those is capped (I forget which, but it's the first one to max), increasing the other one *decreases* the price you can charge.

**Comment by AssenD** [comment] 2023-06-17 09:51
> increasing the other one _decreases_ the price you can charge.

Yes, I saw it and was wondering how and why :)

Also, similar effect had buying more Smart Storage, which is (probably a different?) bug too.
Should I post it as another issue??

**Comment by Hoekstraa** [comment] 2023-06-17 19:47
@d0sboots is there any actionable item here?
Or should this issue be closed?

**Comment by d0sboots** [comment] 2023-06-17 22:38
I was going to leave that up to @AssenD .

> Also, similar effect had buying more Smart Storage, which is (probably a different?) bug too.
Should I post it as another issue??

It's not a bug, just like the awareness/popularity thing isn't a bug. Corp is full of odd mechanical quirks, because that's just how it is. There's an argument to be made for simplifying/streamlining a lot of it, but as it stands right now it's working as intended.

**Comment by Snarling** [comment] 2023-06-19 08:02
Wilson does not increase your awareness/popularity, or the resulting advertising multiplier.

Wilson increases the strength of the `Hire AdVert` action. If you're done buying AdVert, because you've capped Awareness/Popularity to the point where they will hit Infinity if you keep going, then there is no point in buying additional levels of Wilson.

> Also, similar effect had buying more Smart Storage, which is (probably a different?) bug too. Should I post it as another issue??

I'm closing this one, if there is a different issue with Smart Storage please open a new issue

**Closed as not planned by Snarling** 2023-06-19 08:02 UTC
