### ISSUE TITLE
Hotkeys do not follow local keyboard layout

### ISSUE THREAD

**Issue by jweather** [bitburner-official/bitburner-src#669] opened 2023-07-11 12:36 UTC
- Set Windows keyboard layout to US/Dvorak for example
- Ctrl-S and Ctrl-B do not work as expected in Script Editor.  Instead they are Ctrl-O and Ctrl-X respectively, ie, they are mapped to key positions rather than letters
- Bitburner v2.3.1 (100030008)

**Comment by jweather** [comment] 2023-07-11 12:52
https://github.com/bitburner-official/bitburner-src/blob/e4d3a9020e528974c8b58c1919e57accae5c48c9/src/ScriptEditor/ui/ScriptEditorRoot.tsx#L84 is using KeyboardEvent.code=='KeyB' which returns the key position rather than value.  KeyboardEvent.key=='b' should behave as expected.  You can see the same effect reproduced at https://javascript.info/keyboard-events

```
keydown key=a code=KeyA
keyup key=a code=KeyA
keydown key=o code=KeyS
keyup key=o code=KeyS
keydown key=e code=KeyD
keyup key=e code=KeyD
keydown key=u code=KeyF
keyup key=u code=KeyF
```

**Comment by d0sboots** [comment] 2023-07-11 20:43
Duplicate of #420

**Closed as completed by d0sboots** 2023-07-11 20:43 UTC
