### ISSUE TITLE
Bladeburner: Estimated synthoid population goes to zero when doing Raid or Stealth Retirement Operation

### ISSUE THREAD

**Issue by holgero** [bitburner-official/bitburner-src#334] opened 2023-01-20 12:08 UTC
Version of the game is Bitburner v2.1.0 (8f4636cb)

My bladeburner automation chooses the city with the largest estimated population. It does 'Field Analysis' until all estimates for Contracts and Operations have a difference between low and high of less than 0.4 (40%). Sometimes it chooses Raid or Stealth Retirement Operation as next action (usually when there are no more Tracking Contracts left).
This brought me into a situation where the population estimates in all cities went to zero. Here is an excerpt from my save file showing the problem (not in Chongqing, but all other cities):
```json
{
  "Aevum": {
    "ctor": "City",
    "data": {
      "name": "Aevum",
      "pop": 17439443220,
      "popEst": 0,
      "comms": 69,
      "chaos": 48.39585263711599
    }
  },
  "Chongqing": {
    "ctor": "City",
    "data": {
      "name": "Chongqing",
      "pop": 20633579833,
      "popEst": 50140.32173686368,
      "comms": 72,
      "chaos": 48.85015124921137
    }
  },
  "Sector-12": {
    "ctor": "City",
    "data": {
      "name": "Sector-12",
      "pop": 35203050789,
      "popEst": 0,
      "comms": 111,
      "chaos": 66.86265120600348
    }
  },
  "New Tokyo": {
    "ctor": "City",
    "data": {
      "name": "New Tokyo",
      "pop": 21431414727,
      "popEst": 0,
      "comms": 2,
      "chaos": 0
    }
  },
  "Ishima": {
    "ctor": "City",
    "data": {
      "name": "Ishima",
      "pop": 21194733965,
      "popEst": 0,
      "comms": 60,
      "chaos": 35.9714555001924
    }
  },
  "Volhaven": {
    "ctor": "City",
    "data": {
      "name": "Volhaven",
      "pop": 16086554628,
      "popEst": 0,
      "comms": 149,
      "chaos": 56.14294815495731
    }
  }
}
```

I think the problem is caused by https://github.com/bitburner-official/bitburner-src/blob/ac8ea6b5efa7e18d23d3c6d47ac2fd5457fc035b/src/Bladeburner/City.ts#L118 changing the population estimate by the same amount as the population, thus causing the population estimate to drop much faster than the population if the estimate is below the actual population.
My current workaround is to avoid doing Raid or Stealth Retirement Operations.

Would you agree this is a bug and needs fixing?

**Comment by Zelow79** [comment] 2023-01-21 06:27
That isn't a bug. You are just killing the population that fast, and having an inaccurate population estimation is on you, means you should have updated your estimation. This being said, I agree it is rather lame as Raid and Stealth Retirement Operations are pretty much useless for this reason. Suggesting they be improved is fine, but they're not bugs. 

Raids are too harsh on the communities and kill by %.

**Comment by holgero** [comment] 2023-01-29 16:20
Hmm, but the population of the synthoids is still high. I think actually the large real population is the reason that the estimated population dropped so fast. In my opinion it doesn't make sense to reduce the estimation by the same absolute number as the population. Maybe it should be reduced by the same percentage instead.

**Comment by Zelow79** [comment] 2023-01-29 23:55
Bladeburner expects you to update your estimated population frequently.

**Comment by TheMas3212** [comment] 2023-02-14 00:30
Closing this as it is a misunderstanding of mechanics, not a bug

**Closed as completed by TheMas3212** 2023-02-14 00:30 UTC
