### ISSUE TITLE
Corporation: Total Assets NaN

### ISSUE THREAD

**Issue by madfist** [bitburner-official/bitburner-src#1618] opened 2024-08-23 07:12 UTC
version: 2.6.2 (Steam)

Unsure what causes it as I don't often check the Corporation tab, but mostly likely after increasing warehouse/office space from scripts the total assets becomes NaN causing the stock price to slowly drop. Game restart recalculates the assets. Not sure how to investigate further.

![image](https://github.com/user-attachments/assets/8a5a9a10-5a07-4b55-a430-aec8ab691aef)

[bitburnerSave_1724395794_BN9x1.json.gz](https://github.com/user-attachments/files/16725030/bitburnerSave_1724395794_BN9x1.json.gz)

**Comment by bupjae** [comment] 2024-08-23 07:32
This issue is fixed on https://github.com/bitburner-official/bitburner-src/pull/1573 which will be included on next update.

**Comment by gmcew** [comment] 2024-08-23 17:47
Taking your save into the 2.6.3dev; I can't recreate it - so hopefully #1573 is your root cause! If you still have issues in dev or after stable updates; we can reopen/recreate this.

**Closed as completed by gmcew** 2024-08-23 17:47 UTC

**Comment by madfist** [comment] 2024-08-24 12:41
Thanks, once I added the zero-check to my script the problem seems to have gone away.
