### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by OGisidore** [bitburner-official/bitburner-src#926] opened 2023-11-11 17:21 UTC
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v2.5.0 (b87b8b4be)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
* Features: lang=fr-FR cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by d0sboots** [comment] 2023-11-12 08:28
We're going to need a copy of your save game (preferably), or some more info to be able to anything with this. (One of those three checkboxes: either steps to reproduce, or scripts that cause it, or a save game exhibiting the problem)

**Comment by Snarling** [comment] 2023-12-26 12:42
Based on the FR-fr language, this is probably the same issue as #527 #358 where a translation extension tries doing dom manipulation in a way that React doesn't like.

@OGisidore Can you confirm if you were using a translation extension? If so we can close this issue as a duplicate.

**Comment by Snarling** [comment] 2024-02-15 00:47
Duplicate of #527

**Closed as completed by Snarling** 2024-02-15 00:47 UTC
