### ISSUE TITLE
Bug: Installing Augmentations or performing a soft reset reduces gang members ascension multipliers 

### ISSUE THREAD

**Issue by MichaelHorsley** [bitburner-official/bitburner-src#1073] opened 2024-01-31 13:16 UTC
When installing augmentations or performing a soft reset, I've noticed that the gang member multipliers from when they've Ascended are reduced by ~2.53% each time.

I believe it's an issue because of the text on the Gang screen

"Installing Augmentations does NOT reset progress with your Gang."

The image below showing a before and after of performing a soft reset.

![image](https://github.com/bitburner-official/bitburner-src/assets/38311326/d3f565a2-e57d-4f1d-976d-4a5804ba1804)

This is really noticed when installing augmentations in quick succession and can quickly decimate time spent training their stats, as Charisma is particularly slow.

## Version 
Bitburner v2.5.2 (c6141f2ad)

## Steps to reproduce
1. Join a gang
2. Recruit a gang member
3. Train the gang member so that they can gain an ascension multiplier
4. Take note of the multipliers 
5. Perform a soft reset or install augmentations on the player
6. Take note of the multipliers afterwards

**Comment by Caldwell-74** [comment] 2024-01-31 15:54
not a bug but part of the game
its a 5% decrease to their ascension points
https://github.com/bitburner-official/bitburner-src/blob/dev/src/Prestige.ts#L113

**Comment by MichaelHorsley** [comment] 2024-01-31 16:30
> not a bug but part of the game its a 5% decrease to their ascension points https://github.com/bitburner-official/bitburner-src/blob/dev/src/Prestige.ts#L113

First of all thank you for responding and linking to that, how interesting.

I believed it was a bug because of the text on the Gang screen

"Installing Augmentations does NOT reset progress with your Gang." 
Which is definitely technically correct but also slightly mis-leading. 

Potentially something like, "Installing Augmentations will slightly weaken your gang" would be better phrased?

Adding a penalty to the gang does seem strange, but since it's been in there for at least 2 years, I guess no one has really been bothered by it.

I'm happy to close if it's intentional though.

**Comment by Caldwell-74** [comment] 2024-01-31 17:46
i dont think you need to close it because the missleading description is an issue
maybe you can add that one into it so everyone reading this knows about it right away :3

**Comment by LJNeon** [comment] 2024-02-18 21:31
How would this even be explained in the description? It appears that the ascension multiplier is `Math.sqrt(points / 2000)`, so simply mentioning the 5% penalty to points will be incorrect and/or confusing.

**Closed as completed** 2024-02-23 20:58 UTC
